# Generated by hand to introduce queue-backed ticket submissions.
from __future__ import annotations

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketSubmission",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("client_reference", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("status", models.CharField(choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ], default="pending", max_length=32)),
                ("request_payload", models.JSONField(default=dict)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.SET_NULL,
                        related_name="submissions",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="ticketsubmission",
            index=models.Index(fields=["status"], name="tickets_s_status_a2b8f4_idx"),
        ),
        migrations.AddIndex(
            model_name="ticketsubmission",
            index=models.Index(fields=["client_reference"], name="tickets_s_client__d86d86_idx"),
        ),
    ]
